Repository ogawa-ros/ogameasure, pull requests merged in 2022-12, with the labels that each got.

#19 #18 modify map to list
  ogameasure/device/Lakeshore/model218_usb.py
Labels: bug

#21 Version 0.5.5
  .github/workflows/test.yml
  setup.py
Labels: release

#26 Fix exception type to catch
  ogameasure/device/SENA/adios.py
  setup.py
Labels: bug, release

#28 Fix uncaught error on attenuator setting read-out
  ogameasure/communicator/communicator.py
  ogameasure/device/SENA/adios.py
  setup.py
Labels: bug
